language: cpp

compiler:
  - clang
  - gcc
  -clang++
  
jobs:
  fast_finish: true

git:
  submodules: false
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

